### Задание 1

In [21]:
import numpy as np
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [30]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [37]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [58]:
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1])
a_centered_sp

8.0

In [59]:
n = 5
a_centered_sp / (n - 1)

2.0

### Задание 4

In [60]:
np.cov(a.transpose())[0, 1]

2.0

### Просьба объяснить что такое ковариация на следующем уроке.